#!/bin/bash

echo "> let's make sure we're not on master..."
branch=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
if [ "$branch" == "master" ]
then
    echo "Cannot commit to master, please create a dev branch."
    exit 1
else
    echo "$branch ok, continuing..."
fi
echo

. ./linters.sh
